[package]
name = "streamline-core"
version = "0.1.0"
authors = ["Jonathan Whittle <jonathan.m.whittle@gmail.com>"]
edition = "2021"

[dependencies]
byteorder = { version = "1", default-features = false }
enum-as-inner = "0.3.3"
streamline-macros = { path = "../streamline-macros" }
